# -*- coding: utf-8 -*-
"""Extracción_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9oqm3bhluerA3PuV5zYNrZ_b_bAglYD

La extracción o seleccionde datos se puede realizar con fos metodos 1 Metodo Loc y el metodo iloc loc debemos especificar el nombre de la fila o el nombre de la columna iloc debemos especificar la pocisión tal cual haciamos con las listas donde el primer dato inicia en 0
"""

#Importar librerias Pandas
import pandas as pd

#Conectar a Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Leer el archivo CSV palyers 20.csv
df_jugadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/players_20 (1).csv')
df_jugadores.head(10)

#Vamos a fijar el nombre
df_jugadores.set_index('short_name')

#Vamos a sobreescribir el DF para ajustar los cambios de la columna ''short_name'
df_jugadores=df_jugadores.set_index('short_name')
df_jugadores

#Vamos a traer las columnas que necesito y voy actualizar el DF
df_jugadores=df_jugadores[['player_url','long_name','age','dob','height_cm','weight_kg','nationality','club']]
df_jugadores

#Vamos usar por primera ves el método loc()
df_jugadores.loc['Cristiano Ronaldo']

df_jugadores.loc['Neymar Jr']

#Vamos a traer ahora a Messi
df_jugadores.loc['L. Messi', 'club']

df_jugadores.loc['E. Hazard', 'club']

df_jugadores.loc['Pan Ximing', 'club']

# Ahora este metodo de loc tambien nos sirve para obtner todos los datos de una columna
df_jugadores.loc[:,'age']

df_jugadores.loc[:,'weight_kg']

#Para traer todos los datos de una fila lo hacemos de la siguiente manera
df_jugadores.loc['Xiao Mingjie', :]

#Tambien puedo traer dos o mas datos
df_jugadores.loc[['Neymar Jr','Cristiano Ronaldo']]

#Podriamos tambien traer una columna de varias filas
df_jugadores.loc[['Cristiano Ronaldo', 'L. Messi'], 'height_cm']

#Ahora tambíen podemos traer dos columnas pcon dos filas (más)
df_jugadores.loc[['Cristiano Ronaldo', 'Neymar Jr'], ['long_name', 'nationality']]

df_jugadores.loc[['Neymar Jr', 'J. Oblak'], ['height_cm', 'club']]

#Ahora utilicemos el metodo de slicing para cortar el dataframe y mostrar datos que yo escoja
jugadores=['Cristiano Ronaldo', 'L. Messi']
df_jugadores.loc[jugadores,'age':'weight_kg']

jugadores_1=['Cristiano Ronaldo', 'L. Messi', 'Neymar Jr', 'J. Oblak' ]
df_jugadores.loc[jugadores_1,'age':'club']

#si quiero llamar al top 10 usamos index
df_jugadores.index[:10]

columnas=['age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']
df_jugadores.loc['L. Messi': 'M. Salah', columnas]

#si quiero llamar al top 10 usamos index
df_jugadores.index[:21]

df_jugadores.loc['L. Messi': 'R. Lewandowski', columnas]

#ahora seleccionamos elemento con condiciones
columnas=['age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']
df_jugadores['height_cm']>100

df_jugadores.loc[df_jugadores['height_cm']>170, columnas]

#Tambien puedo combinar condiciones
df_jugadores['height_cm']>170
df_jugadores['nationality']=='Colombia'

#Dos o mas condiciones
df_jugadores.loc[
    (df_jugadores['height_cm']>170) &
    (df_jugadores['nationality']=='Colombia'), columnas]