# -*- coding: utf-8 -*-
"""Extracción_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zevt_gw-_VDNSiO_hNkaAYuJ5m433DNo
"""

# a diferencia de .loc, iloc se usa con los indices de cada elemento, esto evita

#Importar librerias Pandas
import pandas as pd

#Conectar a Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Leer el archivo CSV palyers 20.csv
df_jugadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/players_20 (1).csv')
df_jugadores.head(10)

#Ponemos el short name como index
df_jugadores=df_jugadores.set_index('short_name')
df_jugadores.head(3)

#Cortamos solo las
df_jugadores=df_jugadores[['player_url','long_name','age','dob','height_cm','weight_kg','nationality','club']]
df_jugadores

#Ahora usaremos el iloc
df_jugadores.iloc[1]

#para traer dos datos es decir una fila y una columna
df_jugadores.iloc[1, 4]

df_jugadores.iloc[2, 7]

#Para traer el nombre completo de todos los jugadores
df_jugadores.iloc[:, 1]

df_jugadores.iloc[:, 6]

#¿Cómo haría para taer los datos de Oblack?
df_jugadores.iloc[3, :]

df_jugadores.iloc[-1, :]

#Obtener los datos de dos jugadores
df_jugadores.iloc[[0,1],:]

#Traer peso y estatura de Neymar
df_jugadores.iloc[2,[4,5]]

#estatura y Peso
df_jugadores.iloc[[0,1],[4,5]]

#Traer de Messi y Cristiano desde age hasta el final
jugadores=[0,1]
df_jugadores.iloc[jugadores,2:]

#Como traemos los jugaodres top 10
df_jugadores.iloc[:10]