# -*- coding: utf-8 -*-
"""Filtro_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWmue3NW6kLu_bSEUN58esvTiNj-IZzU
"""

#Para ver los datos duplicados puedo usar el metodo duplicate
#Como simepre importamos pandas y prendemos google drive
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(3)

#Para ver los valores duplicados y que se muestre true cuando este duplicado y false si no lo esta, lo hago
df_computadores.duplicated('laptop_ID')

#Aqui muestro los valores duplicados para esta columna, si salen en limpio es porque no hay duplicaods
df_computadores[df_computadores.duplicated('laptop_ID')]

#Puedo usar el value counts para validar si hay un true o todos son false
df_computadores.duplicated('laptop_ID').value_counts()

# Puedo contar o buscar los repetidos en mas de una columna usando duplicated
df_computadores.duplicated(['Product', 'TypeName', 'Inches'])

#Guardo la condición en una variable
duplicados_1=df_computadores.duplicated(['Product', 'TypeName', 'Inches'])

#Ahora filtro directamente en el dataframe
df_computadores[duplicados_1]

#Vamos a ordenar los datos con .sort segun lo que quiero ordenar
df_computadores[duplicados_1].sort_values(['Product', 'TypeName'])

#Vamos a organizarlo de manera diferente
df_computadores=df_computadores[duplicados_1].sort_values(['Company', 'Price_euros'])
df_computadores

df_computadores.value_counts('Company')

#Vamos ahora a manipular el parmetro keep que viene dentro de la función diplicated
#Por defecto este parametro trae el vlaor first
duplicados_firts=df_computadores.duplicated(['Company'], keep='first')

df_computadores[duplicados_firts]

#Para mostrar los no duplicaods de la columna campañia
df_computadores[~duplicados_firts]

#Voy a traer solo las columnas de mi interes
df_computadores[~duplicados_firts][['Company','Price_euros']]

#contamos los datos
df_computadores[~duplicados_firts].value_counts('Company')

#Para mostrar los valores finales de cada repetición
diplicados_last=df_computadores.duplicated(['Company'], keep='last')

#Traifo el elemento final de repetidos
df_computadores[~diplicados_last]

#Para no confundirnos solo traeremos las tres columnas
df_computadores[~diplicados_last][['Company', 'Price_euros']]