# -*- coding: utf-8 -*-
"""Filtro_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIQbrva0vZVjLIMCSbgVUqidXOigqeV0

**Eliminar repetidos**
"""

#Ahora veremos como eliminar o mover datos repetidos
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(3)

#asi elimino los elementos duplicados de una columna
df_computadores.drop_duplicates(['Company'])

df_computadores.drop_duplicates(['Company']).value_counts('Company')

df_computadores.drop_duplicates(['Company'])[['Company', 'Price_euros']]

df_computadores.drop_duplicates(['Company'], keep='last')[['Company','Price_euros']]

#Uso el inplcae para guardar los cambios en el dataframe
#Uso el ignore_index para ignorar la columna id y crear una nueva
df_computadores.drop_duplicates(['Company'], keep='last', inplace=True, ignore_index=True)

df_computadores