# -*- coding: utf-8 -*-
"""Filtro_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDjA4PwVzQwNc4G4zy_L66oGe1VPQxew

Tambien puedo filtrar de dos o más condiciones, las puedo combinar usanso and o or, dependiendo cual sea el caso
"""

import pandas as pd
import numpy as np
#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(5)

df_computadores[df_computadores['Price_euros']>2000]

#Si quiero filtrar por las dos condiciones, es decir que sea mayor a 2000 y que sea Apple debo usar and o or
#Sin embargo, and en pandas es & y o en pandas |
df_computadores[(df_computadores['Company']=='Apple') & (df_computadores['Price_euros']>2000)]

df_computadores[(df_computadores['Company']=='Dell') & (df_computadores['Price_euros']<1000)]

df_computadores[(df_computadores['Company']=='Apple') | (df_computadores['Price_euros']>2000)]

df_computadores[(df_computadores['Company']=='Apple') | (df_computadores['Price_euros']>2000)].value_counts('Company')

#Vamos a filtrar por computadores que sean Apple o Asus y que cuesten menos de 2000
#Primero hagamos las condiciones
df_computadores[((df_computadores['Company']== 'Apple') | (df_computadores['Company']=='Asus')) & (df_computadores['Price_euros']< 2000)]

#Valgan menos de 2000 y mas de 13 pulgadas y la compañia sea Apple
df_computadores[(df_computadores['Company']== 'Apple') & (df_computadores['Inches']>13) & (df_computadores['Price_euros']< 2000)]