# -*- coding: utf-8 -*-
"""Filtro_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzKn7BdqQeG7w67bO2LXZhVTr3gUuHCi
"""

import pandas as pd
import numpy as np
#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(5)

#Creamos primero las condiciones para luego crear la columna
#Vamos a crear dos listas una con las condiciones y la otra con los valores
condiciones=[
    df_computadores['Price_euros']>3000,
    (df_computadores['Price_euros']> 2000) & (df_computadores['Price_euros']<=3000),
    (df_computadores['Price_euros']>800) & (df_computadores['Price_euros']<= 2000),
    df_computadores['Price_euros']<= 800
]

valores=['Carisimo', 'Puede ser', 'Esta mejor', 'Muy barato']

np.select(condiciones, valores)

df_computadores['Testeo_2']= np.select(condiciones, valores)
df_computadores

df_computadores.value_counts('Testeo_2')