# -*- coding: utf-8 -*-
"""Filtro_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19q77Aep3JZDSh64L9CMmUKaAUo9tdyyY

Ahora con un filtro vamos acrear una columna dependiendo lo que este **mostrando**
"""

import pandas as pd
import numpy as np

#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(5)

#Comparación de precios
df_computadores['Price_euros']>2000

#Creamos un arreglo con where para poder ponerle lo que yo quiera
np.where(df_computadores['Price_euros'] >2000, 'Cariñoso', 'Ese es')

df_computadores['Testeo']=np.where(df_computadores['Price_euros'] >2000, 'Cariñoso', 'Ese es')
df_computadores.head(5)

df_computadores['Pantalla']=np.where(df_computadores['Inches'] >13, 'Grande', 'Pequeña')
df_computadores.head(5)

df_computadores.value_counts('Company')

df_computadores['Capacidad']=np.where(df_computadores['Ram']=='16GB','Puedes ver', 'No puedes ver')
df_computadores.head(5)