# -*- coding: utf-8 -*-
"""Filtro_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYQM8ur05t5LvpP_Q0S8hTFWrXMYv3RE

Existe otra forma de filtrar los datos con pandas y usando la función isin()
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(5)

#Vamos a filtar la marca DELL y HP
df_computadores['Company'].isin({'Dell','HP'})

#Filtrar y que se visualice en el DF
df_computadores[df_computadores['Company'].isin(['Dell','HP'])]

#Asi cuento los datos filtrados
df_computadores[df_computadores['Company'].isin(['Dell','HP'])].value_counts('Company')

# Ahora usando isin() voy a filtrar por varias condiciones
#En este caso filtaremos por Notebooks  y ultrabooks y Apple o Asus
#Primero creamos las condiciones
filtro_1=df_computadores['Company'].isin(['Apple','Asus'])
filtro_2=df_computadores['TypeName'].isin(['Notebook', 'Ultrabook'])

#Filtramos los datos
df_computadores[filtro_1 & filtro_2]

#Contamos los datos ahora con los filtros anteriores
df_computadores[filtro_1 & filtro_2].value_counts('TypeName')