# -*- coding: utf-8 -*-
"""Filtro_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pE4JemJf0EZ3-oG9ITz7i-XOBEHRPlig
"""

# Los filtros nos permiten ver solo la información que requerimos, los puedo hacer por contenido o por condición

#Importar librerías
import pandas as pd
import numpy as np

# Vamor a traer el archivo y a convertirlo en un dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores

#Llamamos las primeras filas
df_computadores.head(5)

#Voy a filtrar por company pero lo que va agenerar es un arreglo de verdadero y falso
df_computadores['Company']=='HP'

#Hagamos un segundo filtrado pero con apple
df_computadores['Company']=="Apple"

# Voy a mostrar como se veria filtrado directamente en el datframe
df_computadores[df_computadores['Company']=='Apple']

#Filtrar ahora ASUS
df_computadores['Company']=='Asus'

df_computadores[df_computadores['Company']=='Asus']

#Para contar cuantos registros hay de un filtro, puedo usar value counts
df_computadores[df_computadores['Company']=='Apple'].value_counts('Company')

df_computadores[df_computadores['Company']=='Dell'].value_counts('Company')