# -*- coding: utf-8 -*-
"""Python_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFfk7CD7bg9uoVeVxxU-9QYk_SKtiNWq
"""

#Siempre lo primero que debo hacer es importar pandas y numpy
import pandas as pd
import numpy as np

#Ahora subimos el archivo desde google drive, ya no teenmos que loguearnos de nuevo
df_estudiantes=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/StudentsPerformance (1).csv')
df_estudiantes

#Sigamos con la creaciòn de columnas usando el mètodo assign o el mètodo insert
#Si quiero agregar varias columnas uso assing y tembien si quiero sobreescribir una columna

#Creamos notas de fisica y filosofia aleatorias y las guardamos en variables random es aleatorio
filosofia_score=np.random.randint(1,100, size=1000)
fisica_score=np.random.randint(1,100, size=1000)

#Ahora le pondre un indice a cada fila para que sepa donde va en el dataframe
filosofia_nota=pd.Series(filosofia_score, index=np.arange(0,1000))
fisica_nota=pd.Series(fisica_score,index=np.arange(0,1000))

#Ahora lo que voy hacer es poner las nuevas columnas a mi dataframe, usando asing
df_estudiantes.assign(filosofia_score=filosofia_nota, fisica_score=fisica_nota)

df_estudiantes=df_estudiantes.assign(filosofia_score=filosofia_nota, fisica_score=fisica_nota)
df_estudiantes

#Ahora vamos usar el metodo insert, el metodo insert es diferente porque me permite especificar donde yo voy a identificar esa columna
#Al usar el metodo insert debemos tener cuidado porque no me devuelve copias sino que el cambio queda hecho de una vez
df_estudiantes.insert(1,'ED_SCORE', fisica_nota)

df_estudiantes

