# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lk24DkzU2HskIHlIqVbl8T_417ZO_nYw
"""

# Web scraping es un metodo que me permite tomar información que esta disponible en la web y
#Asi funciona gran parte del modelo de gpt
#Esto no es una practica ilegal
import pandas as pd

#Hay muchas formas de hacer web scraping sin embargo vamos hacerlo simple
datos_futbol=pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

datos_futbol

#Ahora vamos a cambiar los nombres a las columnas para poder verlo de una mejor manera
datos_futbol.rename(columns={'Date':'Fecha',
                    'HomeTeam':'Local',
                    'AwayTeam':'Visitante',
                    'FTHG':'Goles Locales',
                    'FTAG':'Goles Visitante'})

"""Estos son los links que voy a scrapear


*   https://www.football-data.co.uk/mmz4281/2425/E0.csv
*   https://www.football-data.co.uk/mmz4281/2425/E1.csv


*   https://www.football-data.co.uk/mmz4281/2425/E2.csv
*   https://www.football-data.co.uk/mmz4281/2425/E3.csv


*   https://www.football-data.co.uk/mmz4281/2425/EC.csv






"""

#La siguiente es la estructura que podemos ver en el link
'https://www.football-data.co.uk/mmz4281/'+'2425'+'/'+'E0'+'.csv'

#Ya se que la raiz es la misma entonces la guardo en una variable que se llame ruta
ruta='https://www.football-data.co.uk/mmz4281/'

#Ahora lo que voy a hacer es crear una lista con los campeonatos o terminaciones
campeonatos=['E0','E1','E2','E3','EC']
enlaces=[]
#Para que esto funcione debo recorrer la lista con un loop, a esta práctica se le conoce como link dinámico, una vez recotrra la lista debo reemplazar el valor para que el enlace funcione
for campeonato in campeonatos:
  df_links=pd.read_csv(ruta +'2425' +'/' + campeonato + '.csv')
  enlaces.append(df_links)

#Voy a medir la longitud de la lista
len(enlaces)

enlaces[-1]

